apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kube-system
spec:
  containers:
  - image: nginx:1.19.2
    name: nginx
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /healthz
        port: 6443
        scheme: HTTPS
    volumeMounts:
    - mountPath: /etc/nginx/nginx.cfg
      name: nginxconf
      readOnly: true
    - mountPath: /etc/nginx/kube-apiserver.conf
      name: kubeapiserverconf
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/nginx/nginx.conf
      type: FileOrCreate
    name: nginxconf
  - hostPath:
      path: /etc/nginx/kube-apiserver.conf
      type: FileOrCreate
    name: kubeapiserverconf
status: {}