- name: copy netplan file
  become: true
  template:
    src: "../templates/99-cloud-init.yaml.j2"
    dest: "/etc/netplan"

- name: change hostname
  become: true
  shell: |
    if [ `uname -n` != "{{ inventory_hostname }}" ];then
      hostnamectl set-hostname "{{ inventory_hostname }}"
      echo true
    else
      echo false
    fi
  register: hostname_change_flag
    
- name: reboot
  become: true
  reboot: 
  when: hostname_change_flag.stdout_lines[0] == "true"

- name: apt update & apt upgrade
  become: true
  apt:
    autoclean: yes
    upgrade: safe
    update_cache: yes
    state: latest   

- name: install golang-cfssl
  run_once: true
  become: true
  apt: 
    update_cache: yes
    name: 
    - golang-cfssl

- name: download kubectl, kubelet
  get_url:
    url: "{{ item }}"
    dest: $HOME
    mode: "0755"
  with_items:
    - https://storage.googleapis.com/kubernetes-release/release/v{{ K8s_version }}/bin/linux/arm64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v{{ K8s_version }}/bin/linux/arm64/kubelet

- name: mv kubectl, kubelet
  become: true
  file:
    path: "{{ item }}"
    mode: "0755"
  with_items: 
    - kubectl
    - kubelet
      
- name: copy kubectl, kubelet to /usr/local/bin
  become: true
  synchronize: 
    src: "{{ home_dir }}/{{ item }}"
    dest: "/usr/local/bin"
  with_items:
    - kubectl
    - kubelet
  delegate_to: "{{ inventory_hostname }}"

- name: copy some addon manifests
  copy:
    src: "../files/addon/"
    dest: "$HOME/K8s_manifest/"

