- name: set timezone to Asia/Tokyo
  become: true
  timezone:
    name: Asia/Tokyo

- name: install ntp and ntpdate
  become: true
  apt:
    name: 
      - ntpdate
      - ntp

- name: stop ntp.service
  become: true
  systemd:
    state: stopped
    name: ntp

- name: adjust time by ntpdate
  become: true
  shell: |
    STATUS=bad
    NTP_DATE=`ntpdate {{ ntp_server }}`

    if [ -n "`echo $NTP_DATE | grep "adjust time server" `" ];then
      STATUS=ok
    fi

    echo $STATUS
  register: ntpdate_status
  retries: 50
  delay: 5
  until: ntpdate_status.stdout_lines[0]=='ok'

- name: remove default ntpserver in /etc/ntp.conf
  become: true
  replace:
    path: /etc/ntp.conf
    regexp: "^pool"

- name: DEV | set ntpserver in /etc/ntp.conf
  become: true
  lineinfile:
    path: /etc/ntp.conf
    state: present
    insertafter: "EOF"
    line: "pool {{ ntp_server }} iburst"
    validate: "grep -w pool %s"
  when: stage=='dev'

- name: PROD | set ntpserver in /etc/ntp.conf
  become: true
  lineinfile:
    path: /etc/ntp.conf
    state: present
    insertafter: "EOF"
    line: "server {{ ntp_server }} iburst"
    validate: "grep -w -e server -e pool %s"
  when: stage=='prod'

- name: reload ntpd by systemd
  become: true
  systemd:
    daemon_reload: true
    state: restarted
    name: ntp

- name: waiting for adjusting the time ...
  become: true
  shell: |
    STATUS=bad

    if [ -n "`ntpq -p | grep "*"`" ];then
      STATUS=ok
    fi

    echo $STATUS
  register: ntpq_status
  retries: 50
  delay: 5
  until: ntpq_status.stdout_lines[0]=='ok'